Setup docker
ibwgr/warranty-tracker pull request #25
Opened 2021-01-23 14:23 UTC by ladral

Actually the docker compose contains just the database container. Additional containers can be added later.

2021-01-31 17:51 UTC, Hubbacca requested changes

2021-01-31 17:51 UTC, Hubbacca commented on docker-compose.yml
> +    image: mariadb:latest
latest!=aktuell. Fixe Version verwenden.

2021-01-31 17:51 UTC, Hubbacca commented on README.md
> +3. fire up your terminal and go to the root directory of the project
works like a charm, but that docker must be started before running the command 'docker-compose up' should also be stated.

2021-01-31 17:51 UTC, Hubbacca commented on docker-compose.yml
> +      - 3333:3306
Theoretically can Port 3333 be replaced with 3306 (mariadb standard port). Maybe an addition in the installation guide like: "Attention, Port 3306 (or 3333 whatever is taken) must not be occupied"

2021-02-01 05:30 UTC, ladral commented on docker-compose.yml
> +      - 3333:3306
The readme file contains now the information about the port

2021-02-01 05:30 UTC, ladral commented on README.md
> +3. fire up your terminal and go to the root directory of the project
updated the instruction in the readme file.

2021-02-01 05:30 UTC, ladral commented on docker-compose.yml
> +    image: mariadb:latest
changed to version 10.5

2021-02-01 20:26 UTC, merged